import Head from "next/head"
import { Main } from "../components"
import  styles from "../styles/mainPage.module.css"


export default function Home() {
	return (
		<div className={styles.container} >
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main />
		</div>
	)
}
